apiVersion: apps/v1                                                                                                                                                           â”‚
kind: DaemonSet
metadata:
  name: openebs-jiva-csi-node
  namespace: openebs
spec:
  template:
    spec:
      hostPID: true